### ISSUE TITLE
Smaller image with Alpine Linux

### ISSUE THREAD

**Issue by BlinkyStitt** [IronicBadger/docker-booksonic#5]
The container is a lot smaller if you use one of the *-alpine builds on https://hub.docker.com/_/tomcat/

You will have to change the ffmpeg install command slightly, too.

**Comment by ironicbadger** [comment]
I don't disagree. I think my buddies at linuxserver.io are cooking up an alpine based container. I just threw this together to keep my wife happy. :)

**Comment by BlinkyStitt** [comment]
Cool. The linuxserver.io images are great
